[build]
  command = "bash ./netlify-build.sh"
  publish = "build/web"

# Redirección para recuperación de contraseña
[[redirects]]
  from = "/reset-password"
  to = "/netlify-redirect/reset-password.html"
  status = 200

[[redirects]]
  from = "/reset-password-debug"
  to = "/netlify-redirect/reset-password-debug.html"
  status = 200

# Redirección para compartir partidos
[[redirects]]
  from = "/match/:id"
  to = "/netlify-redirect/match.html"
  status = 200

# Redirección para las rutas de la aplicación Flutter
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200