[build]
  command = "bash ./netlify-build.sh"
  publish = "build/web"

# Redirección específica para reset-password (debe ir antes que la regla comodín)
[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200

# Redirección para las rutas de la aplicación Flutter (debe ir al final)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200