[build]
  command = "flutter build web"
  publish = "build/web"

# Redirección para las rutas de la aplicación Flutter
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirección por defecto
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200