[build]
  publish = "build/web"
  command = "flutter build web --release"

# Redirecciones específicas para partidos
[[redirects]]
  from = "/match/*"
  to = "/index.html"
  status = 200

# Redirección por defecto a la página principal
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200